### ISSUE TITLE
please provide a netcoreapp2.0 binary

### ISSUE THREAD

**Issue by 0x53A** [enricosada/dotnet-mergenupkg#3]
ref https://github.com/fsprojects/Paket/pull/2664#issuecomment-325068376

Hi @enricosada, do you think it would be possible to update [dotnet-mergenupkg](https://www.nuget.org/packages/dotnet-mergenupkg/) and provide a netcoreapp2.0 binary?

Otherwise usage in the Sdk 2.x is a bit clumsy, because I still need to install the 1.0.x runtime in parallel somehow.

I've hacked together something so I can continue working on paket: https://github.com/enricosada/dotnet-mergenupkg/compare/master...0x53A:master

If you want I can try to clean that up, fully migrate json => fsproj and send a pr.

**Comment by enricosada** [comment]
@0x53A good idea, i'll do it

**Comment by enricosada** [comment]
@0x53A done and released [v2.0.0](https://github.com/enricosada/dotnet-mergenupkg/releases/tag/v2.0.0)

this support both sdk 1.0 and 2.0

nuget: https://www.nuget.org/packages/dotnet-mergenupkg/2.0.0

**Comment by 0x53A** [comment]
Thank you
